### ISSUE TITLE
May not work with 7.4 anymore

### ISSUE THREAD

**Issue by TrueType** [cobwebch/flush_language_cache#1]
Hi Francois,
we are using your extension. In 7.4 it may not be working any more:

```
<t3err>
No backend function registered for ajaxID "language_cache::flushCache".
</t3err>
```

**Comment by fsuter** [comment]
Oh, thanks for notifying me. It's hard to keep up with 7.x development. I'll to fix this as quickly as possible.

**Comment by fsuter** [comment]
A short note to say that this is not forgotten. I have a working solution locally, but it relies on an internal API, so I'm waiting for advice from core devs. I may do a release soon anyway and can correct later if applicable.

**Comment by TrueType** [comment]
You may always push your changes in a new branch (e.g. development) to have others watch or try out your latest changes.

**Comment by fsuter** [comment]
Relevant discussion is here: https://forge.typo3.org/issues/57096

So my change is fine and I'll publish when I have a bit of time. I just need to test it with 6.2.
