### ISSUE TITLE
translation in layout isn't populated

### ISSUE THREAD

**Issue by DavidBruchmann** [cobwebch/flush_language_cache#13]
Using something like this : `{f:translate(key: 'LLL:EXT:sitepackage/Resources/Private/Language/formConsent.xlf:consentMail.accident')}`, changed translations never populate. I've to mention that the code is included in the layout, and not in template or partial.  
Also a flush of the whole cache in the backend doesn't help. Actually I've to change the filename to get the change shown.  
This is some kind strange and perhaps related to my missing knowledge about cache details, at least it did cost me some hours to find out how I can circumvent the annoying behavior.

TYPO3 11.5.12
PHP 7.4.29
Instance is running in ddev container, so the OS is Linux

**Comment by fsuter** [comment]
Hi. If flushing the whole cache does not help, then this would be a Core issue and not related to this extension. What this extension does, it just to flush the "l10n" cache using the Core's `CacheManager` class.

The "l10n" cache is normally found in folder `var/cache/data/l10n`. When you flush just the language cache with this extension or flush all the cache from the backend, the directory should be empty. Is that the case?

**Comment by DavidBruchmann** [comment]
Thanks for the explanation.
No, the folder is not emptied, might be an issue with access rights I suppose.
The files have '-rwxr-xr-x ', so I've to check how to adjust rights or ownership in ddev.
