### ISSUE TITLE
TYPO3 dependency at least 8.7.14

### ISSUE THREAD

**Issue by sevenflip** [cobwebch/flush_language_cache#8]
Since TYPO3 8.7.14 the argument *$objectString* for the function *getTSConfig()* in *TYPO3\CMS\Core\Authentication\BackendUserAuthentication* is optional, before it was required:

https://github.com/TYPO3/TYPO3.CMS/commit/d7a68b8af05a40f83ef8fefeec71fc319e015a6a#diff-ef54b14802e1367284dcb31a3a78eabc

https://get.typo3.org/release-notes/TYPO3_CMS_8.7.14
Commit d7a68b8af0

**Comment by fsuter** [comment]
Thanks for noticing this. I will update the dependencies.
